commitizen:
  changelog_file: CHANGELOG.md
  changelog_incremental: false
  changelog_start_rev: 2.0.0
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch$prerelease
  update_changelog_on_bump: true
  version: 2.0.2
  version_files:
  - pyproject.toml: version
