name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            changelog_increment_filename: body.md
      - name: Create Additional Body
        run: |
          echo "## Install the library!\nPyPi page: https://pypi.org/project/pygess-py/\nInstall using: `pip install pygess-py` (on Windows) `pip3 install pygess-py` (on Mac)" > add_body.md
      - name: Create Release Notes
        id: create_release_notes
        run: |
          echo "## Install the library!\nPyPi page: https://pypi.org/project/pygess-py/\nInstall using: `pip install pygess-py` (on Windows) `pip3 install pygess-py` (on Mac)" >> body.md.md
          echo "::set-output name=body::$(cat body.md)"
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          append_body: true
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          name: "Release ${{ env.REVISION }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
