name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          body_path: "body.md"
          append_body: true
          body: |
            ## Install the library! 
            PyPi page: https://pypi.org/project/pygess-py/
            Install using: `pip install pygess-py` (on Windows) `pip3 install pygess-py` (on Mac)"
          tag_name: ${{ env.REVISION }}
          name: "Release ${{ env.REVISION }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
